version: 2.1
jobs:
  build:
    docker:
      - image: 'ubuntu:20.10'
    steps:
      - run:  apt-get update -y
      - run:  apt-get install -y git curl flex bison libssl-dev ca-certificates make bc zip gcc libc6-dev python3-minimal wget
      - run:
          name: Cloning Repo
          command:  git clone  --depth 1 https://github.com/Nicklas373/kernel_xiaomi_msm8953-4.9 /root/build/c
      - run:  
          name: Compilation
          command: wget https://raw.githubusercontent.com/Accipiter7/kernel_xiaomi_msm8953-4.9/lineage-17.1/build.sh |
                   ls -al |
                   pwd

workflows:
  version: 2.1
  cooking:
    jobs:
      - build
